"""
How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
"""

from time import time

if __name__ == "__main__":
	start = time()
	answer = len(set((pow(a,b) for a in xrange(2,101) for b in xrange(2,101))))
	elapsed = time() - start
	print "Found %s after %s seconds" % (answer, elapsed)