"""
Problem 12:
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import time

def gen_traingle_numbers(n_triangles):
	triangle, current_number, yielded = 1, 2, 0
	while yielded < n_triangles:
		yield triangle
		triangle = triangle + current_number
		current_number += 1
		yielded += 1

def n_factors(n):    
    result = set()
    for i in range(1, int(n ** 0.5) + 1):
        div, mod = divmod(n, i)
        if mod == 0:
            result |= {i, div}
    return len(result)

if __name__ == "__main__":
	start = time.time()
	while True:
		n_t = int(raw_input("Number of Triangles:"))
		if n_t == 0:
			break
		for ind, t in enumerate(gen_traingle_numbers(n_t),1):
			a,b,c = (ind, t, n_factors(t))
			if c >= 500:
				print "%d\t%d\t%s" % (a,b,c)
			
